expo install expo-font
expo install expo-localization
expo install expo-sqlite
expo install fsevents
expo install i18n-js
expo install lodash
expo install lottie-ios
expo install lottie-react-native
expo install mobx
expo install mobx-react
expo install moment
expo install react-native-easy-grid
expo install react-native-keyboard-aware-scroll-view
expo install react-native-really-awesome-button
expo install react-native-root-toast
expo install react-native-svg-transformer
expo install react-native-svg-uri
expo install react-native-swiper
expo install react-native-swiper-flatlist
expo install react-native-typography
expo install react-native-vector-icons
